### ISSUE TITLE
Can't launch TeMiCross, "Invalid group"

### ISSUE THREAD

**Issue by bielids** [trgwii/TeMiCross#3]
When trying to launch the bot I keep getting the following error: 

```
(node:1572) UnhandledPromiseRejectionWarning: SyntaxError: Invalid regular expression: /^\[(?<time>\d{2}:\d{2}:\d{2})] \[(?<thread>.*?)/(?<loglevel>.*?)\]: (?<user>[a-zA-Z0-9_]{1,16}) has made the advancement \[(?<advancement>.+)\]$/: Invalid group
    at new RegExp (<anonymous>)
    at Parser.mapObjIndexed (/usr/local/lib/node_modules/temicross/client/parser/index.js:43:11)
    at XWrap.f (/usr/local/lib/node_modules/temicross/node_modules/ramda/src/mapObjIndexed.js:32:16)
    at XWrap.@@transducer/step (/usr/local/lib/node_modules/temicross/node_modules/ramda/src/internal/_xwrap.js:12:17)
    at _arrayReduce (/usr/local/lib/node_modules/temicross/node_modules/ramda/src/internal/_reduce.js:11:34)
    at _reduce (/usr/local/lib/node_modules/temicross/node_modules/ramda/src/internal/_reduce.js:45:12)
    at mapObjIndexed (/usr/local/lib/node_modules/temicross/node_modules/ramda/src/mapObjIndexed.js:31:10)
    at f2 (/usr/local/lib/node_modules/temicross/node_modules/ramda/src/internal/_curry2.js:29:14)
    at Parser (/usr/local/lib/node_modules/temicross/client/parser/index.js:42:19)
    at run (/usr/local/lib/node_modules/temicross/client/run.js:17:17)
(node:1572) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1572) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

I have tried setting up the bot both using `tmc botwrap` and the `tmc wrap` method but they both end up with the same error. The error mentions `Invalid group`. Am I using the wrong chat ID?

**Comment by trgwii** [comment]
Which node version are you using?
