### ISSUE TITLE
Cant set-up bot

### ISSUE THREAD

**Issue by Playez** [trgwii/TeMiCross#6]
Hello, I'm trying to set up a bot with tmc botwrap, using magma, Minecraft 1.12.2 but getting this error
`? Notify Telegram about game updates? Yes
node:events:355
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:773:11)
    at Socket._write (node:net:785:8)
    at writeOrBuffer (node:internal/streams/writable:395:12)
    at Socket.Writable.write (node:internal/streams/writable:340:10)
    at Interface.parser.send (/usr/lib/node_modules/temicross/client/run.js:25:28)
    at run (/usr/lib/node_modules/temicross/bot/run.js:137:9)
    at Object.run (/usr/lib/node_modules/temicross/botwrap/run.js:8:14)
    at /usr/lib/node_modules/temicross/cli/index.js:41:11
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:188:8)
    at emitErrorCloseNT (node:internal/streams/destroy:153:3)
    at processTicksAndRejections (node:internal/process/task_queues:81:21) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}`

I tried to install it from sudo or from my user, nothing changed. node.js version= 15.11.0

**Comment by trgwii** [comment]
What is "magma"?

**Comment by Playez** [comment]
> What is "magma"?

Magma is a server core to combine mods and plugins at the same time
